In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
os.listdir()

['test.csv',
 'attacks.csv',
 'Project Week 2 Draft.ipynb',
 'Project Week 2.ipynb',
 '.ipynb_checkpoints']

In [3]:
!pwd

/Users/joaootaviomeirellesratton/Desktop/Ironhack/Labs_mycodes/Projects/Week_2

In [4]:
df = pd.read_csv('/Users/joaootaviomeirellesratton/Desktop/Ironhack/Labs_mycodes/Projects/Week_2/attacks.csv', sep=(','), encoding=('latin-1'))

In [5]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Species,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,White shark,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,NaN,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2 m shark,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,"Tiger shark, 3m",A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
date_values = list(df['Year'].unique())

In [7]:
date_values

[2018.0,
 2017.0,
 nan,
 2016.0,
 2015.0,
 2014.0,
 2013.0,
 2012.0,
 2011.0,
 2010.0,
 2009.0,
 2008.0,
 2007.0,
 2006.0,
 2005.0,
 2004.0,
 2003.0,
 2002.0,
 2001.0,
 2000.0,
 1999.0,
 1998.0,
 1997.0,
 1996.0,
 1995.0,
 1984.0,
 1994.0,
 1993.0,
 1992.0,
 1991.0,
 1990.0,
 1989.0,
 1969.0,
 1988.0,
 1987.0,
 1986.0,
 1985.0,
 1983.0,
 1982.0,
 1981.0,
 1980.0,
 1979.0,
 1978.0,
 1977.0,
 1976.0,
 1975.0,
 1974.0,
 1973.0,
 1972.0,
 1971.0,
 1970.0,
 1968.0,
 1967.0,
 1966.0,
 1965.0,
 1964.0,
 1963.0,
 1962.0,
 1961.0,
 1960.0,
 1959.0,
 1958.0,
 1957.0,
 1956.0,
 1955.0,
 1954.0,
 1953.0,
 1952.0,
 1951.0,
 1950.0,
 1949.0,
 1948.0,
 1848.0,
 1947.0,
 1946.0,
 1945.0,
 1944.0,
 1943.0,
 1942.0,
 1941.0,
 1940.0,
 1939.0,
 1938.0,
 1937.0,
 1936.0,
 1935.0,
 1934.0,
 1933.0,
 1932.0,
 1931.0,
 1930.0,
 1929.0,
 1928.0,
 1927.0,
 1926.0,
 1925.0,
 1924.0,
 1923.0,
 1922.0,
 1921.0,
 1920.0,
 1919.0,
 1918.0,
 1917.0,
 1916.0,
 1915.0,
 1914.0,
 1913.0,
 1912.0,
 1911.0,
 1910.0,
 1909.0,
 1908.0,
 1907.0,
 1906.0,
 1905.0,
 1904.0,
 1903.0,
 1902.0,
 1901.0,
 1900.0,
 1899.0,
 1898.0,
 1897.0,
 1896.0,
 1895.0,
 1894.0,
 1893.0,
 1892.0,
 1891.0,
 1890.0,
 1889.0,
 1888.0,
 1887.0,
 1886.0,
 1885.0,
 1884.0,
 1883.0,
 1882.0,
 1881.0,
 1880.0,
 1879.0,
 1878.0,
 1877.0,
 1876.0,
 1875.0,
 1874.0,
 1873.0,
 1872.0,
 1871.0,
 1870.0,
 1869.0,
 1868.0,
 1867.0,
 1866.0,
 1865.0,
 1864.0,
 1863.0,
 1862.0,
 1861.0,
 1860.0,
 1859.0,
 1858.0,
 1857.0,
 1856.0,
 1855.0,
 1853.0,
 1852.0,
 1851.0,
 1850.0,
 1849.0,
 1847.0,
 1846.0,
 1845.0,
 1844.0,
 1842.0,
 1841.0,
 1840.0,
 1839.0,
 1837.0,
 1836.0,
 1835.0,
 1834.0,
 1832.0,
 1831.0,
 1830.0,
 1829.0,
 1828.0,
 1827.0,
 1826.0,
 1825.0,
 1823.0,
 1822.0,
 1819.0,
 1818.0,
 1817.0,
 1816.0,
 1815.0,
 1812.0,
 1811.0,
 1810.0,
 1808.0,
 1807.0,
 1805.0,
 1804.0,
 1803.0,
 1802.0,
 1801.0,
 1800.0,
 1797.0,
 1792.0,
 1791.0,
 1788.0,
 1787.0,
 1786.0,
 1785.0,
 1784.0,
 1783.0,
 1780.0,
 1779.0,
 1776.0,
 1771.0,
 1767.0,
 1764.0,
 1758.0,
 1753.0,
 1751.0,
 1749.0,
 1755.0,
 1748.0,
 1742.0,
 1738.0,
 1733.0,
 1723.0,
 1721.0,
 1703.0,
 1700.0,
 1642.0,
 1638.0,
 1637.0,
 1617.0,
 1595.0,
 1580.0,
 1555.0,
 1554.0,
 1543.0,
 500.0,
 77.0,
 5.0,
 0.0]

In [8]:
# Counting nulls by row
mask = df.isnull().sum(axis=1) >= 23
mask

0        False
1        False
2        False
3        False
4        False
         ...
25718     True
25719     True
25720     True
25721     True
25722     True
Length: 25723, dtype: bool

In [9]:
df['quantity'] = df.isnull().mean(axis=1)

In [10]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,quantity
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,0.083333
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,0.125000
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,0.125000
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,0.166667
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25718,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25720,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25721,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000
25722,xx,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.958333

In [11]:
df = df.drop(df[df.quantity >= 0.85].index)

In [12]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,quantity
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,0.083333
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,0.125000
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,0.125000
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,0.166667
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,0.208333
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,0.250000
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,0.208333
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,...,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,0.291667
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,0.166667

In [13]:
df.columns

Index(['Case Number', 'Date', 'Year', 'Type', 'Country', 'Area', 'Location',
       'Activity', 'Name', 'Sex ', 'Age', 'Injury', 'Fatal (Y/N)', 'Time',
       'Species ', 'Investigator or Source', 'pdf', 'href formula', 'href',
       'Case Number.1', 'Case Number.2', 'original order', 'Unnamed: 22',
       'Unnamed: 23', 'quantity'],
      dtype='object')

In [14]:
df.drop_duplicates(subset=list(df.columns))

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,quantity
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,0.083333
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,0.125000
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,0.125000
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,0.166667
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,0.208333
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,0.250000
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,0.208333
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,...,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,0.291667
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,0.166667

In [15]:
null_cols = df.isnull().mean()
null_cols

Case Number               0.000159
Date                      0.000000
Year                      0.000317
Type                      0.000635
Country                   0.007934
Area                      0.072199
Location                  0.085687
Activity                  0.086322
Name                      0.033323
Sex                       0.089654
Age                       0.449222
Injury                    0.004443
Fatal (Y/N)               0.085528
Time                      0.532212
Species                   0.450333
Investigator or Source    0.002698
pdf                       0.000000
href formula              0.000159
href                      0.000000
Case Number.1             0.000000
Case Number.2             0.000000
original order            0.000000
Unnamed: 22               0.999841
Unnamed: 23               0.999683
quantity                  0.000000
dtype: float64

In [16]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,quantity
0,2018.06.25,25-Jun-2018,2018.0,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,"R. Collier, GSAF",2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,0.083333
1,2018.06.18,18-Jun-2018,2018.0,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,"K.McMurray, TrackingSharks.com",2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,0.125000
2,2018.06.09,09-Jun-2018,2018.0,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,"K.McMurray, TrackingSharks.com",2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,0.125000
3,2018.06.08,08-Jun-2018,2018.0,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,"B. Myatt, GSAF",2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,0.166667
4,2018.06.04,04-Jun-2018,2018.0,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,A .Kipper,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,0.166667
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,"H. Taunton; N. Bartlett, p. 234",ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,0.208333
6298,ND.0004,Before 1903,0.0,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,"H. Taunton; N. Bartlett, pp. 233-234",ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,0.250000
6299,ND.0003,1900-1905,0.0,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,"F. Schwartz, p.23; C. Creswell, GSAF",ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,0.208333
6300,ND.0002,1883-1889,0.0,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,...,"The Sun, 10/20/1938",ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,0.291667
6301,ND.0001,1845-1853,0.0,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,S.W. Baker,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,0.166667

In [17]:
list(df['Year'].unique())

[2018.0,
 2017.0,
 nan,
 2016.0,
 2015.0,
 2014.0,
 2013.0,
 2012.0,
 2011.0,
 2010.0,
 2009.0,
 2008.0,
 2007.0,
 2006.0,
 2005.0,
 2004.0,
 2003.0,
 2002.0,
 2001.0,
 2000.0,
 1999.0,
 1998.0,
 1997.0,
 1996.0,
 1995.0,
 1984.0,
 1994.0,
 1993.0,
 1992.0,
 1991.0,
 1990.0,
 1989.0,
 1969.0,
 1988.0,
 1987.0,
 1986.0,
 1985.0,
 1983.0,
 1982.0,
 1981.0,
 1980.0,
 1979.0,
 1978.0,
 1977.0,
 1976.0,
 1975.0,
 1974.0,
 1973.0,
 1972.0,
 1971.0,
 1970.0,
 1968.0,
 1967.0,
 1966.0,
 1965.0,
 1964.0,
 1963.0,
 1962.0,
 1961.0,
 1960.0,
 1959.0,
 1958.0,
 1957.0,
 1956.0,
 1955.0,
 1954.0,
 1953.0,
 1952.0,
 1951.0,
 1950.0,
 1949.0,
 1948.0,
 1848.0,
 1947.0,
 1946.0,
 1945.0,
 1944.0,
 1943.0,
 1942.0,
 1941.0,
 1940.0,
 1939.0,
 1938.0,
 1937.0,
 1936.0,
 1935.0,
 1934.0,
 1933.0,
 1932.0,
 1931.0,
 1930.0,
 1929.0,
 1928.0,
 1927.0,
 1926.0,
 1925.0,
 1924.0,
 1923.0,
 1922.0,
 1921.0,
 1920.0,
 1919.0,
 1918.0,
 1917.0,
 1916.0,
 1915.0,
 1914.0,
 1913.0,
 1912.0,
 1911.0,
 1910.0,
 1909.0,
 1908.0,
 1907.0,
 1906.0,
 1905.0,
 1904.0,
 1903.0,
 1902.0,
 1901.0,
 1900.0,
 1899.0,
 1898.0,
 1897.0,
 1896.0,
 1895.0,
 1894.0,
 1893.0,
 1892.0,
 1891.0,
 1890.0,
 1889.0,
 1888.0,
 1887.0,
 1886.0,
 1885.0,
 1884.0,
 1883.0,
 1882.0,
 1881.0,
 1880.0,
 1879.0,
 1878.0,
 1877.0,
 1876.0,
 1875.0,
 1874.0,
 1873.0,
 1872.0,
 1871.0,
 1870.0,
 1869.0,
 1868.0,
 1867.0,
 1866.0,
 1865.0,
 1864.0,
 1863.0,
 1862.0,
 1861.0,
 1860.0,
 1859.0,
 1858.0,
 1857.0,
 1856.0,
 1855.0,
 1853.0,
 1852.0,
 1851.0,
 1850.0,
 1849.0,
 1847.0,
 1846.0,
 1845.0,
 1844.0,
 1842.0,
 1841.0,
 1840.0,
 1839.0,
 1837.0,
 1836.0,
 1835.0,
 1834.0,
 1832.0,
 1831.0,
 1830.0,
 1829.0,
 1828.0,
 1827.0,
 1826.0,
 1825.0,
 1823.0,
 1822.0,
 1819.0,
 1818.0,
 1817.0,
 1816.0,
 1815.0,
 1812.0,
 1811.0,
 1810.0,
 1808.0,
 1807.0,
 1805.0,
 1804.0,
 1803.0,
 1802.0,
 1801.0,
 1800.0,
 1797.0,
 1792.0,
 1791.0,
 1788.0,
 1787.0,
 1786.0,
 1785.0,
 1784.0,
 1783.0,
 1780.0,
 1779.0,
 1776.0,
 1771.0,
 1767.0,
 1764.0,
 1758.0,
 1753.0,
 1751.0,
 1749.0,
 1755.0,
 1748.0,
 1742.0,
 1738.0,
 1733.0,
 1723.0,
 1721.0,
 1703.0,
 1700.0,
 1642.0,
 1638.0,
 1637.0,
 1617.0,
 1595.0,
 1580.0,
 1555.0,
 1554.0,
 1543.0,
 500.0,
 77.0,
 5.0,
 0.0]

In [18]:
df.query('Year == 77')

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,Investigator or Source,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,quantity
6175,0077.00.00,77 A.D.,77.0,Unprovoked,NaN,Ionian Sea,NaN,Sponge diving,males,M,...,Perils mentioned by Pliny the Elder (23 A.D. t...,77AD-Pliny.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,0077.00.00,0077.00.00,128.0,NaN,NaN,0.291667

In [21]:
df['Year'] = df['Year'].apply(lambda x: int(x) if x > 0 else 'N/A')

In [22]:
list(df['Year'].unique())

[2018,
 2017,
 'N/A',
 2016,
 2015,
 2014,
 2013,
 2012,
 2011,
 2010,
 2009,
 2008,
 2007,
 2006,
 2005,
 2004,
 2003,
 2002,
 2001,
 2000,
 1999,
 1998,
 1997,
 1996,
 1995,
 1984,
 1994,
 1993,
 1992,
 1991,
 1990,
 1989,
 1969,
 1988,
 1987,
 1986,
 1985,
 1983,
 1982,
 1981,
 1980,
 1979,
 1978,
 1977,
 1976,
 1975,
 1974,
 1973,
 1972,
 1971,
 1970,
 1968,
 1967,
 1966,
 1965,
 1964,
 1963,
 1962,
 1961,
 1960,
 1959,
 1958,
 1957,
 1956,
 1955,
 1954,
 1953,
 1952,
 1951,
 1950,
 1949,
 1948,
 1848,
 1947,
 1946,
 1945,
 1944,
 1943,
 1942,
 1941,
 1940,
 1939,
 1938,
 1937,
 1936,
 1935,
 1934,
 1933,
 1932,
 1931,
 1930,
 1929,
 1928,
 1927,
 1926,
 1925,
 1924,
 1923,
 1922,
 1921,
 1920,
 1919,
 1918,
 1917,
 1916,
 1915,
 1914,
 1913,
 1912,
 1911,
 1910,
 1909,
 1908,
 1907,
 1906,
 1905,
 1904,
 1903,
 1902,
 1901,
 1900,
 1899,
 1898,
 1897,
 1896,
 1895,
 1894,
 1893,
 1892,
 1891,
 1890,
 1889,
 1888,
 1887,
 1886,
 1885,
 1884,
 1883,
 1882,
 1881,
 1880,
 1879,
 1878,
 1877,
 1876,
 1875,
 1874,
 1873,
 1872,
 1871,
 1870,
 1869,
 1868,
 1867,
 1866,
 1865,
 1864,
 1863,
 1862,
 1861,
 1860,
 1859,
 1858,
 1857,
 1856,
 1855,
 1853,
 1852,
 1851,
 1850,
 1849,
 1847,
 1846,
 1845,
 1844,
 1842,
 1841,
 1840,
 1839,
 1837,
 1836,
 1835,
 1834,
 1832,
 1831,
 1830,
 1829,
 1828,
 1827,
 1826,
 1825,
 1823,
 1822,
 1819,
 1818,
 1817,
 1816,
 1815,
 1812,
 1811,
 1810,
 1808,
 1807,
 1805,
 1804,
 1803,
 1802,
 1801,
 1800,
 1797,
 1792,
 1791,
 1788,
 1787,
 1786,
 1785,
 1784,
 1783,
 1780,
 1779,
 1776,
 1771,
 1767,
 1764,
 1758,
 1753,
 1751,
 1749,
 1755,
 1748,
 1742,
 1738,
 1733,
 1723,
 1721,
 1703,
 1700,
 1642,
 1638,
 1637,
 1617,
 1595,
 1580,
 1555,
 1554,
 1543,
 500,
 77,
 5]

In [27]:
df['Species '].fillna('Unknown').value_counts()

Unknown                                                2839
White shark                                             163
Shark involvement prior to death was not confirmed      105
Invalid                                                 102
Shark involvement not confirmed                          88
                                                       ...
A 2' shark was seen in the area by witnesses              1
"grey shark"                                              1
Wobbegongs                                                1
Nurse shark, 6'                                           1
60 cm to 90 cm [2' to 3'] blacktip or spinner shark       1
Name: Species , Length: 1549, dtype: int64

In [29]:
import re

In [66]:
df['Species_copy'] = df['Species ']

In [70]:
list(df['Species '].unique())

['White shark',
 nan,
 '2 m shark',
 'Tiger shark, 3m',
 'Tiger shark',
 "Lemon shark, 3'",
 "Bull shark, 6'",
 'Grey reef shark',
 'Invalid incident',
 'Tawny nurse shark, 2m',
 'Shark involvement not confirmed',
 'Questionable',
 '3 m shark',
 'White shark, 3.5 m',
 'White shark, 2.5 m',
 "6' shark",
 'Juvenile bull shark',
 'Bull shark',
 "Tiger shark, 12'",
 'Wobbegong shark',
 '3.5 m shark',
 '1.8 m shark',
 'Blacktip shark',
 'Juvenile white shark,  2.7 to 3.2 m',
 'Bull shark, 2 m',
 'Possibly a wobbegong',
 'Injury believed caused by an eel, not a shark',
 'Galapagos shark?',
 '2m shark',
 'Bull shark, 3 m ',
 'Grey reef shark. 2 m',
 'small shark',
 'Wobbegong shark?',
 'Juvenile nurse shark',
 "Nurse shark. 5'",
 'Tiger shark, female',
 'Some drowned but other may have been killed by blue sharks',
 'White shark, 4.6 m',
 'Cookiecutter shark',
 'Wobbegong shark, 1 m',
 'White shark, 4.5 m',
 'Spinner shark, 4 to 5 feet',
 'Tiger shark, 8 to 10 feet',
 "8' shark",
 'Death may have been due to drowning',
 "5' shark",
 "4' to 5' shark",
 'Porbeagle, 1.5 m',
 'White shark, 3.5m',
 "5' to 6' shark",
 'White shark, 3 to 3.5m ',
 'Nurse shark',
 'White shark, 3 m',
 'Shark involvement questionable',
 "White shark, 5' to 7'",
 'Possibly a juvenile blacktip shark',
 'Oceanic whitetip shark, 1.8 to 2 m',
 "4' shark",
 "White shark, 10'",
 'A small shark',
 "Sandtiger shark  2'",
 "Blue shark 6'",
 '"A small shark"',
 "White shark, 11' to 13'",
 "White shark, 8' to 10'",
 "White shark, 9'",
 "Bull shark, 4' to 5'",
 'Tiger shark, 100 kg',
 'Shark involvement prior to death not confirmed',
 'No shark invovlement ',
 'Bull shark, 2m',
 'White shark, 4 m',
 'Seven-gill shark',
 '3m shark, probably a smooth hound',
 "3' shark",
 "9' shark",
 'Shark involvement highly doubtful',
 'No shark invovlement - it ws a publicity stunt',
 "Bull shark, 5' to 7'",
 "10' shark",
 'Lemon shark',
 'Bull shark, 1.5',
 'Lemon shark pup',
 "White shark, female, 14'",
 'Caribbean reef shark',
 'Bull shark, 4 m',
 'Bull shark, 1 m',
 'a small shark',
 'Wobbegong shark, 2m',
 'Broadnose sevengill shark, 1.5 m',
 " 6' to 8' shark",
 "3' to 4' shark",
 "Tiger shark, 10'",
 'Invalid',
 'Bull shark, 3.5 m',
 "Tiger shark, 10' ",
 'Blue shark',
 "Nurse shark, 4'",
 'reef shark, 1m',
 "White shark, 10' to 12'",
 "Lemon shark, 9'",
 'Angel shark',
 'dogfish shark',
 'Tawny nurse shark',
 "Caribbean reef shark, 4.5'",
 "3' to 5' shark",
 "Said to involve an 8' shark but more likely damage caused by debris",
 '3+ m shark',
 'Mako shark',
 'Bronze whaler sharks x 3',
 "Blacktip shark, 4'",
 "Nurse shark, 2'",
 "Mako shark, 1.5 m [5'] ",
 'Grey reef shark, 2 m',
 "Bull shark, 7'",
 'Tiger shark, 2.5 m',
 'Nurse shark, 2.5-ft',
 'Bronze whaler',
 'Sandtiger shark',
 'No shark involvement',
 "Reef shark, 5'",
 'Bull sharks x 2',
 "Tiger shark, 14'",
 "Silky shark, 6.5'",
 "Bronze whaler shark, 6'",
 'Tiger shark, 1.5 m ',
 'Galapagos shark',
 "Spinner shark, 7'",
 'Bull shark, 2.8 to 3.1 m',
 "Spinner shark, 5'",
 "Tiger shark, 7'",
 'Hammerhead sp.',
 "Tiger shark, 13' ",
 "Blacktip shark, 4' to 5'",
 "Blacktip shark, 5' to 6'",
 "White shark, 19'",
 'juvenile shark',
 "Tiger shark, 13'",
 'Hammerhead shark',
 "White shark, 11' to 12'",
 'Hammerhead shark.',
 "4' shark?",
 "White shark, 10' to 12' ",
 "White shark, 13'",
 "Hammerhead shark. 6' to 7'",
 "Blacktip or spinner shark, 4'",
 "Thought to involve a 3' to 4' shark, but shark involvement not confirmed",
 'White shark, 3.9 to 4.2 m',
 'Mako shark, 100-lb',
 'Bronze whaler shark, 1.5m',
 "White shark, 7'",
 'Shark involvement not cofirmed',
 "6' to 7' shark",
 'White shark, 2m to 3 m',
 "Bull shark, 5'",
 'small nurse shark',
 'Bull shark, 2.5 m',
 '1m to 1.2 m shark',
 '3- to 4-foot shark',
 'White shark, 6 m',
 'Blue shark, 8 to 9 feet',
 'Tiger shark, 8 to 12 feet',
 'Blacktip Reef shark ',
 'Tiger shark, 3.5 m',
 '3.5 to 4 m shark',
 '2 m to  3 m shark',
 'Bull shark, 1.3 m',
 '5 m shark',
 '1.5 m shark',
 'White shark or oceanic whitetip shark',
 'Raggedtooth shark, 1.3 m',
 'White shark, 4 to 5 m',
 'Shark involvement prior to death still to be determined',
 'Shark involvement not confirmed & highly unlikely',
 'Goblin shark',
 "2' shark",
 "12' to 14' shark",
 '1 m shark',
 "Bull shark, 3' to 4'",
 "White shark, 18' to 20'",
 "8' to 10' shark",
 '2 white shark: 13\' & 9"8"',
 "7' shark",
 "White shark, 12' to 14'",
 'Spinner shark',
 'Spinner shark or blacktip shark',
 "4' to 6' shark",
 "Bull shark, 4.5' ",
 'reef shark',
 " Bull shark, 8'",
 "Bull shark, 9' to 10'",
 " Bull shark, 5'",
 "4' tp 5' shark",
 'Possibly juvenile tiger shark',
 '1.8 metre shark',
 "6' to 8' shark",
 " White shark, 7' ",
 "Oceanic whitetip shark'",
 "Caribbean reef shark, 7' to 8'",
 ' Lemon shark, 3.5 m',
 " Sandbar shark, 3' to 4'",
 ' Bull shark, 1.2m ',
 '3m shark',
 ' Tawney nurse shark, 1m',
 " white shark, 15' ",
 'Cow shark',
 'reef shark?',
 ' Raggedtooth shark, 2m',
 '3 m to 4 m white shark',
 'Blacktip or spinner shark?',
 'Blacktip reef shark ',
 '7-gill shark?',
 '1m shark',
 '7-gill shark',
 'Oceanic whitetip shark',
 'Reported to involve a bull shark',
 'White shark, 3m ',
 "Tiger shark, 10' to 12'",
 ' Wobbegong shark, 1.6 to 1.8m ',
 'Tiger shark, 3m ',
 'Thought to involve a white shark',
 "White shark, 10 '",
 'Reported to involve a white shark',
 'Blacktip reef shark, 1m',
 'Thought to involve a bull shark',
 'Reported to involve a 4 m white shark',
 "Whitetip reef shark, 4' to 6'",
 'Nurse shark?',
 'Small bull shark',
 'Salmon shark',
 "Mako shark, 5'",
 'Tiger shark?',
 "Bull shark, 8'",
 "Bull shark, 6' to 8'",
 "Tiger shark, 8' to 10' ",
 "Possibly a Bull shark, 3'",
 "Lemon shark, 4'",
 'Wobbegong, 2m',
 'Grey nurse shark, 3m',
 'Possibly a blacktip reef shark',
 'shark involvement not confirmed',
 'Raggedtooth shark, 1.5 m',
 'Tiger shark, 4.8 m',
 'Bronze whaler shark, 2.5m',
 '"small sharks"',
 'White shark, 4m',
 'White shark, 5m',
 "Tiger shark, 15'",
 'Bronze whaler shark, 3m',
 '2.5 m shark',
 'Bull shark, 2m ',
 "Tiger shark, 6'",
 "2' to 3' shark",
 "Tiger shark, 8'",
 "Tiger shark, 10' to 12' ",
 "White shark, 15' to 16' ",
 'Possibly a 3 m bull shark',
 "3.5' to 4' shark",
 "Porbeagle shark, 7'",
 '4.5 m shark',
 "Lemon shark, 4' to 5' ",
 'Lemon shark, 2.5m to 3m ',
 'White shark or bronze whaler',
 'Salmon shark suspected, but unlikely',
 "14' to 18'shark",
 "15' shark",
 'possibly a bull shark',
 'a small reef shark',
 'small blacktip shark?',
 'Blacktip shark ',
 'Blue shark, 2.5m',
 'White shark, 2 m',
 '18" to 24" shark',
 'Bull shark, 3m',
 "Tiger shark, 8' to 9' ",
 'White shark, 4 m to 5m ',
 'White shark, 6m ',
 "Tiger shark, 10'  ",
 'White shark, 4m ',
 'Possibly a bull shark',
 "Possibly a 5' to 6' bull shark",
 'Tawny nurse shark, 40cm',
 'Grey nurse shark',
 'White shark, 7m',
 'Blue shark, 70-kg blue shark',
 'White shark, 2.7 m',
 'Allegedly a 4 m tiger shark',
 "7' to 8' shark ",
 'White shark, 2.5m',
 "White shark, 15' to 16'",
 'Raggedtooth shark',
 "White shark, 15'",
 'Port Jackson shark, 1m',
 "10' to 12' shark",
 '2 to 2.5 m shark',
 'Tiger shark, 2m',
 "6' shark, possibly a blactip or spinner shark",
 "White shark, >6'",
 "Possibly a 5' to 6' sandtiger shark",
 '4 m shark',
 'Grey reef shark ',
 'White shark, 3m to 4m',
 'Bull shark, 3m female',
 "White shark, 5' k",
 "Oceanic whitetip shark, 7'",
 "Sevengill shark, 6' to 8'",
 'Zambesi shark',
 ' Tiger shark, 2.8m',
 "Sandbar shark, 8'",
 "Bull shark, 12'",
 'reef shark, 1.5m',
 "1' to 2' shark",
 'possibly a bronze whaler shark',
 ' Bull shark, 2.5 m',
 'Blacktip shark pup',
 'Bull shark, 2.5m',
 '3 m to 4 m shark',
 'White shark x 2',
 'Oceanic whitetip shark, 2.5m ',
 'Mako shark ',
 'Oceanic whitetip shark, 2.5m, female',
 "Porbeagle shark, 8' ",
 "White shark, 14' to 18' ",
 'Bull shark, 1.4m ',
 "Possibly a 6' lemon shark",
 'Shark involvement prior to death was not confirmed',
 'Possibly a small blacktip shark',
 "Sandtiger shark, 4' to 5'",
 'A small spinner shark',
 'Nurse shark, juvenile ',
 "Blue shark, 7'",
 '20 to 30kg shark',
 "Lemon shark, 6'",
 "14' shark",
 "Oceanic whitetip shark, 6'",
 'Possibly a blue shark',
 'Wobbegong shark, 1.6m',
 '2 m to 3 m shark',
 "Spinner shark, 6'",
 'Thought to involve a juvenile hammerhead shark',
 'Whitetip reef shark, 1m',
 'Zambesi shark, 2m ',
 'White shark, 2.8 to 3 m ',
 "Sandtiger shark, 8'",
 'Thresher shark',
 "Bull shark, 10'",
 'Spurdog',
 "White shark, 5' to 6' juvenile ",
 'White shark, 2m',
 'Tiger shark, 12',
 'Bull shark?',
 "Caribbean reef shark, 6'",
 "Nurse shark, 6'",
 'Thought to involve a Bronze whale shark, 2m',
 'Shark involvement probable, but not confirmed',
 'Oceanic whitetip shark, 2.5 to 3m',
 '80 kg shark',
 "5' to 8' shark",
 'blacktip or spinner shark',
 "White shark, 12' to 15' female",
 'Bronze whaler shark?',
 'Blacktip reef shark pup',
 'Thought to involve a cookie cutter shark',
 'Wobbegong shark, 60cm',
 'Blue shark, 1m',
 '2.6 m shark',
 'White shark, 2.5m ',
 'Bull shark, 2.7 m ',
 "White shark, 12' ",
 'White shark, 5.5 m ',
 'White sharks',
 'Dusky shark, 2m',
 'Mako shark, 3m',
 'Broadnose sevengill shark',
 'White shark, 4m to 5m ',
 '4 to 5m white shark',
 'Raggedtooth shark, 2m',
 'White shark, 4.5 to 5 m ',
 'Zambesi shark?',
 'Bronze whaler shark',
 ' reef shark, 1.8m',
 '5 m white shark',
 "+3' shark",
 "2' to 3' juvenile shark",
 "White shark, 14' to 16' ",
 "8' bull shark or Caribbean reef shark",
 "8' white shark or 7-gill shark",
 "3'  shark",
 "2'  shark",
 "2' to 3' reef shark",
 'Starry smoothhound shark, 1m',
 "Bull shark, 6' to 7'",
 'White shark, 4.5m',
 "4.5 to 5' shark",
 'Basking shark',
 'Tiger sharks in area',
 '2 small bull sharks',
 'Bull shark, 1.8m',
 "White shark, 12' to 15'",
 'Tiger shark, 2.3m ',
 "Tiger shark, 13' female",
 'Reported by media as shark attack, but shark involvement prior to death was not confirmed',
 'Shark involvement not confirmed; thought to be a barracuda bite',
 "1.5' to 2' shark",
 "2.5' shark",
 'A bull shark, according to some of the divers on the boat',
 "Goblin shark, 4.2'",
 'Blacktip shark, 2m',
 'Mako shark, 90kg',
 'Bronze whaler shark, 4m',
 "Nurse shark, 10'",
 'Possibly a hammerhead shark',
 '"a small shark"',
 'Not a shark attack; it was a hoax',
 '2.27 m shark',
 '1.5 to 2 m shark',
 "Blacktip shark, 5'",
 'Oceanic whitetip sharks were in the vicinity',
 'Gray reef shark',
 "9.5' shark?",
 "Nurse shark, 2' to 3' ",
 'Possibly a spinner shark',
 "White shark, 12'",
 'Sand shark',
 "Possibly a 6' bull shark",
 ' ',
 "Possibly a 10' bull shark",
 'Bronze whaler shark, 1.5 m ',
 "3' small spotted catshark, Scyliorhinus canicula",
 "Bull shark, 5' ",
 'Questionable Incident',
 "Lemon shark, 6' female ",
 'A 10-year-old 94-pound pregnant blacktip reef shark',
 'Lesser spotted dogfish, Scyliorhinus canicula, less than 80 cm in length',
 'White shark, 2m ',
 "Tiger shark, 14' ",
 'Lemon shark, >1 m ',
 "Bull shark, 10' ",
 'White shark, 3m',
 '2.4 m shark',
 '24" to 30" shark',
 "6' to 8' shark, possibly a tiger shark",
 '2.5 to 3 m shark',
 '2 to 3 m shark',
 "White shark, 12' to 15' ",
 'Raggedtooth shark, 150-kg',
 'White shark, 5m ',
 'Bull shark, 1.5m ',
 "White shark, 16' ",
 "1' to 4' shark",
 "3' to 3.5' shark",
 'White shark, 3.5m ',
 'small catsharks',
 'White shark?',
 'Thought to involve a mako shark, but possibly a sea lion',
 "Bull shark, 4' to 5' ",
 'Angel shark, 1.2m ',
 'Shark involvement not confirmed, injury may have been caused by a bluefish',
 'Bull or tiger shark',
 "5' to 6' spinner or bull shark",
 '1.8 m blacktip "reef" shark',
 "Possibly a 1' to 3' blacktip or spinner shark",
 "14' white shark",
 "Tiger shark, 8' to 12'",
 "Tiger shark, 15' female",
 "Grey reef shark, 5' to 8' ",
 'Wobbegong shark, 2 m ',
 "Bull shark, 4' to bull shark",
 'Bronze whaler shark, a  juvenile ',
 'Raggedtooth shark, 2.5 m to 3 m ',
 '3 m, 600-kg shark',
 "Tiger shark, 5' ",
 'Bronze whaler shark, 2 m',
 "5' to 7' shark",
 '4.5 m white shark',
 "12' to 18' shark",
 "12' shark",
 '3.5 m white shark',
 'Said to involve a 1.5 m shark',
 'Whitetip reef shark',
 '4 m white shark',
 '3 m white shark',
 'Raggedtooth shark, 2.5m ',
 "12' to 14' white shark",
 "18' white shark",
 "Tiger shark, less than 10'",
 'Caribbean reef sharks',
 'Tiger shark, 3 m ',
 "14' to 16' white shark",
 "4 m [13'] white shark",
 "2 m [6.75'] shark, 200-kg shark T",
 'juvenile white shark',
 'Possibly a sandbar shark or small blacktip shark',
 "1.8 m [6'] shark",
 "3.5 m [11.5']shark",
 "[4.5' to 5'] shark",
 "[4' to 5']",
 "1.8 m [6'] bull shark",
 'On 8/13/2005 anglers from New Zealand caught a 2.8 m [9\'3"], 140-kg [309-lb] shark at the same spot. It was believed this was the same shark that killed Alysha',
 'Unknown, but it was reported that a shark tooth was recovered from the wound',
 "3 m [10'] white shark",
 "Mr. Burgess of ISAF announced the injury was the bite of a 1.8 m [6'], 2- to 3-year old white shark. Subsequent investigation revealed there was  no shark involvement in this incident",
 '"small shark"',
 '18" to 36" shark',
 "Tiger shark, 3 m [10']",
 "2 m [6.75'] copper shark",
 "1.8 m [6'] blacktip shark",
 'small hammerhead shark',
 "4 m [13'] shark",
 "6 m [20'] white shark",
 "Sandtiger shark, 2.1 m [7'] ",
 "Bronze whaler shark, 4.3 m [14'] ",
 "Nurse shark, 3' ",
 "Tiger shark, 2.4 m [8']",
 "1.8 m [6'] Caribbean reef shark",
 "3 m [10'] shark",
 "Bronze whaler shark, 2 m to 3 m [6.75' to 10']  ",
 '4.5 m & 5 m white shark ',
 "5.5 m [18'] white shark",
 "2.5 m [8.25'] bull shark",
 "2 m [6.75'] white shark",
 "Bronze whaler shark, 2.4 m [8'] ",
 "1.8 m to 2.4 m [6' to 8'] white shark",
 "Tiger shark, 2.4 m to 3.7 m [8' to 12'] ",
 "Raggedtooth shark, 1.5 to 2 m [5' to 6.75']",
 'Thought to involve a 2.5 m bull or tiger shark',
 "Tiger shark, 3 m [10'] ",
 "2.4 m [8'] shark",
 "0.9 m to 1.2 m [3' to 4'] white shark",
 "4.9 m to 5.5 m [16' to 18'] white shark",
 "1.2 m [4'] shark",
 "3 m to 4 m [10' to 13']  white shark",
 "1.2 m to 1.5 m [4' to 5'] shark",
 "Longfin mako shark, 3.5 m [11.5'], 350-kg [772-lb] ",
 '2 sharks, 4.5 m & 3 m ',
 '"black tipped" shark',
 '9\'2" white shark',
 "Bronze whaler shark, 2.5 m [8.25'] ",
 "0.9 m to 1.5 m [3' to 5'] shark",
 "2.4 m to 3.7 m [8' to 12'] shark",
 "1,5 m [5'] Caribbean reef shark (Carcharhinus  perezi)",
 "Mako shark, 1.8 m [6']",
 "Wobbegong shark, 1.2 m [4'] k",
 "White shark, 5.5 m [18']",
 'small sharks',
 "5 m [16.5'] white shark",
 "1.2 m [4'] bull shark",
 'bull shark',
 "Tiger shark, 2.4 m to 3 m [8' to 10'] ",
 "Bronze whaler shark, 1.5 m [5'] ",
 "2 m [6.75'] sevengill  shark",
 '60 cm [23.6"] blind or brown shark',
 "4 m to 5 m [13' to 16.5'] white shark",
 'Possibily a  1.5 to 2 m sandtiger shark',
 'Shark involvement doubtful',
 'Bull shark, 1.65 m [5\'5"] was speared & killed',
 'Bull shark, 132-kg [291-lb] ',
 "Mako shark, 3 m to 4 m [10' to 13'] ",
 "Raggedtooth shark, 3.5 m [11.5'] ",
 'Shortfin mako shark',
 "Wobbegong shark, 1.2 m [4'] ",
 "Tiger shark, 4 m [13']  ?",
 '2.5 oceanic whitetip shark',
 "Nurse shark, 60 cm to 90 cm [2' to 3'] ",
 "1.5 m [5'] shark, either a bronze whaler or a grey nurse shark",
 '1.2 m [4\'] "grey-colored shark"',
 '2 m cow shark',
 "4.5 m to 5.5 m [15' to 18'] white shark",
 "3.5 m [11.5'] white shark",
 'Unidentified species',
 "1.5 m to 1.8 m [5' to 6'] shark",
 "2.1 m  [7'] bull shark",
 "8' great hammerhead shark",
 "106 cm [3.5']  shark",
 '\x93small brown shark\x94',
 "3.7 m to 4.3 m [12' to 14'] shark",
 '"sand shark"',
 "1.8 m [6'] reef shark - or a 2.1 m to 2.4 m [7' to 8'] grey-colored shark",
 "0.9 m to 1.2 m [3' to 4'] shark",
 'A \x93small\x94 shark',
 '15 cm to 20 cm [6" to 8"] bite diameter just below left knee',
 "Mako shark, 3 m [10']",
 "60 cm [2'] captive shark",
 "2.5 m [8.25'] white shark",
 'Species unidentified',
 "Thought to involve a 2 m [6.75'] grey nurse shark",
 "Thought to involve a >2 m [6.75'] bull shark",
 'Reported to involve a hammerhead shark',
 'White shark, 4 m white shark',
 'Wobbegong shark, 1m',
 'Shark involvement not confirmed, injury may be due to a stingray',
 "3 m to 4.5 m [10' to 15'] white shark",
 "2.4 m to 3 m [8' to 10'] grey colored shark",
 "1.8 m to 2.1 m [6' to 7']\xa0 Caribbean Reef Shark ",
 'Possibly a bull shark or tiger shark',
 'Blacktip or spinner shark',
 "3.5' to 4.5' shark",
 "1.2 m [4'] blacktip shark",
 "Tiger shark, 1.5 m [5']k",
 "3 m to 3.7 m [10' to 12'] shark",
 "1' to 2' hammerhead or bonnethed shark",
 "0.9 m  to 1.2 m [3' to 4'] shark",
 "Nurse shark, 1.5 m [5'] ",
 "Sandtiger shark, 3 m [10'] ",
 "1.2 m [4'] blacktip or sandbar shark",
 "Bull shark, 1.8 m to 2.1 m [6' to 7'] ",
 'Mako shark, 400-lb ',
 "1.2 m to 1.5 m [4' to 5'] shark, possibly a bull shark",
 "Tiger shark, 2.4 m to 2.7 m [8' to 9']  ",
 "0.9 m to 1.2 m [3' to 4'] shark; Tooth fragment recovered from hand",
 '\xa0 ',
 "1.5 to 2.5 m [5' to 8.25'] copper shark",
 "3.7 m to 4.3 m [12' to 14'] white shark",
 '1 m  shark',
 "3' blacktip shark",
 "2.1 m to 2.4 m [7' to 8'] shark",
 "White shark, 6m [20']",
 'Bull shark, 400-lb ',
 "0.9 m [3'] shark",
 'Nurse shark, 1m ',
 "Spinner shark, 3' to 4' ",
 'Shark involvement prior to death unconfired',
 '1.5 m [5\'] "whaler shark"',
 'C. leucas tooth fragment recovered from kayak',
 'Unidentified',
 "Tiger shark, 1.8 m [6'] ",
 "Mako shark, 2 m [6.75'] ",
 "Tiger shark, 1.8 m [6']",
 'Questionable incident - shark bite may have precipitated drowning',
 "2' to 3.5' shark",
 "12' sandtiger shark",
 'A large white shark was filmed by divers on a local wreck 2 days prior to the incident.',
 "1.5 m [5'] shark",
 "3 m [10'] bull shark",
 'Possibly  a blacktip or spinner shark',
 "3' shark, possibly  a blacktip or spinner shark",
 "Blacktip shark, 5' to 6' ",
 "1.9 m [6.5'] bull shark",
 "Mako shark, 14' ",
 "0.9 m  [3'] shark",
 "Bull shark, 2.3 m [7.5'] ",
 "White shark, 2.4 m to 3 m [8' to 10'] ",
 "1.2 m to 1.5 m [4.5' to 5'] shark",
 "White shark, 2.7 m to 3 m [9' to 10'] ",
 'Possibly a juvenile blacktip or spinner shark',
 "Possibly a 1.5 m [5'] blacktip or spinner shark",
 '1 m shark, possibly whitetip reef shark',
 "White shark, 2.7 m [9'] ",
 "Spinner shark, 1.2 m to 1.5 m [4' to 5'] ",
 "Tiger shark, 8' ",
 "White shark, 5 m [16.5'] ",
 "Bronze whaler shark, 2.5 m [8.25']  k",
 "2 m [6.75'] shark",
 "White shark, 4.3 m [14'] ",
 '1.8 m to 2.4 m [6\' to 8\'] "black finned shark"',
 "6 m [20'] shark",
 'White shark, 4.5 m [14\'9"] ',
 "Porbeagle shark, 3 m [10']rk",
 'Tiger shark, 4 m ',
 "1.2 m to 1.8 m [4' to 6'] shark",
 "White shark, 4.9 m [16'] ",
 "Tiger shark, 1.8 m to 2.4 m [6' to 8'] ",
 "2.1 to 2.4 m [7' to 8'] shark",
 "Blacktip shark, 2' ",
 "White shark, 4.3 m [14']",
 "White shark, 4 m to 5 m [13' to 16.5'] ",
 '100-kg [221-lb] dead blue shark',
 'White shark, 2.5 m ',
 "60 cm to 90 cm [2' to 3'] shark",
 "White shark, 3.5 m [11.5']  male ",
 'Thought to involve a Zambesi shark',
 "A 2' shark was seen in the area by witnesses",
 "Thought to involve a 2.7 m [9'], 400-lb bull shark",
 'Tiger shark, 3.7 m to 4.5 m [12\' to 14\'9"]  ',
 "Blacktip shark, 2.4 m to 3 m [8' to 10'] ",
 'Shark involvement  not confirmed',
 "Nurse shark, 1.5 m [5']",
 "1.8 m [6'] grey-colored shark",
 "Grey reef shark, 2 m [6.75'] ",
 "Lemon shark, 2.1  m to 2.4 m [7' to 8'] ",
 "Tiger shark, 0.9 m to 1.5 m [3' to 5'] ?",
 "Nurse shark, 1.2 m [4'] ",
 "0.9 m [3'] shark,  probably a blacktip or spinner shark",
 "Bull shark, 2.4 m [8']",
 "Blacktip shark, 1.2 m to 1.8 m [4' to 6'] ",
 'Tiger sharks & bull sharks (20 sharks in all)',
 "Tiger shark, 4 m [13'] ?",
 "2 m to 2.5 m [6.75'  to 8.25'] shark",
 'Shark involvement  questionable',
 "Shortfin mako shark, 3 m to 3.4 m [10' to 11'] ",
 'Miami, a 60 cm blacktip  shark and two 60 cm bamboo catsharks',
 'Sevengill shark',
 'Thought to involve a white, bull or tiger shark',
 "White shark, 3 m [10'] ",
 '1.3 to 1.6 m shark',

In [75]:
df.query('Country == USA')

UndefinedVariableError: name 'USA' is not defined

In [77]:
df['species_treated'] = df['species_treated'].apply(lambda x: re.sub('.*[Ww]hite.*', 'white shark', x))
df['species_treated'] = df['species_treated'].apply(lambda x: re.sub('.*[Tt]iger.*', 'tiger shark', x))
df['species_treated'] = df['species_treated'].apply(lambda x: re.sub('.*[Bb]ull.*', 'bull shark', x))
df['species_treated'] = df['species_treated'].apply(lambda x: re.sub('.*[Ll]emon.*', 'lemon shark', x))

In [78]:
df_known = df.loc[df['species_treated'] != 'Unknown']

In [69]:
df_known['species_treated'].value_counts()

white shark                                           667
tiger shark                                           283
bull shark                                            178
Shark involvement prior to death was not confirmed    105
Invalid                                               102
                                                     ...
Raggedtooth shark, 2.7 m [9']                           1
 Tawney nurse shark, 1m                                 1
Goblin shark                                            1
Bronze whaler shark, 1.5 m [5']                         1
Broadnose sevengill shark                               1
Name: species_treated, Length: 947, dtype: int64

In [54]:
df['href formula'].values

array(['http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.25-Wolfe.pdf',
       'http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.18-McNeely.pdf',
       'http://sharkattackfile.net/spreadsheets/pdf_directory/2018.06.09-Denges.pdf',
       ...,
       'http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0003-Ocracoke_1900-1905.pdf',
       'http://sharkattackfile.net/spreadsheets/pdf_directory/ND-0002-JulesPatterson.pdf',
       'http://sharkattackfile.net/spreadsheets/pdf_directoryND-0001-Ceylon.pdf'],
      dtype=object)

In [43]:
df['species_treated'].value_counts()

Unknown                                               2839
white shark                                            667
tiger shark                                            283
bull shark                                             178
Shark involvement prior to death was not confirmed     105
                                                      ...
Remains recovered from 3 sharks                          1
 Grey nurse shark,  3 m [10']                            1
Raggedtooth shark, 2.7 m [9']                            1
Mako shark, 14'                                          1
1.3 to 1.6 m shark                                       1
Name: species_treated, Length: 948, dtype: int64

In [41]:
df

,Case Number,Date,Year,Type,Country,Area,Location,Activity,Name,Sex,...,pdf,href formula,href,Case Number.1,Case Number.2,original order,Unnamed: 22,Unnamed: 23,quantity,species_treated
0,2018.06.25,25-Jun-2018,2018,Boating,USA,California,"Oceanside, San Diego County",Paddling,Julie Wolfe,F,...,2018.06.25-Wolfe.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.25,2018.06.25,6303.0,NaN,NaN,0.083333,white shark
1,2018.06.18,18-Jun-2018,2018,Unprovoked,USA,Georgia,"St. Simon Island, Glynn County",Standing,AdysonÂ McNeely,F,...,2018.06.18-McNeely.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.18,2018.06.18,6302.0,NaN,NaN,0.125000,Unknown
2,2018.06.09,09-Jun-2018,2018,Invalid,USA,Hawaii,"Habush, Oahu",Surfing,John Denges,M,...,2018.06.09-Denges.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.09,2018.06.09,6301.0,NaN,NaN,0.125000,Unknown
3,2018.06.08,08-Jun-2018,2018,Unprovoked,AUSTRALIA,New South Wales,Arrawarra Headland,Surfing,male,M,...,2018.06.08-Arrawarra.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.08,2018.06.08,6300.0,NaN,NaN,0.166667,2 m shark
4,2018.06.04,04-Jun-2018,2018,Provoked,MEXICO,Colima,La Ticla,Free diving,Gustavo Ramos,M,...,2018.06.04-Ramos.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,2018.06.04,2018.06.04,6299.0,NaN,NaN,0.166667,"Tiger shark, 3m"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6297,ND.0005,Before 1903,N/A,Unprovoked,AUSTRALIA,Western Australia,Roebuck Bay,Diving,male,M,...,ND-0005-RoebuckBay.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0005,ND.0005,6.0,NaN,NaN,0.208333,Unknown
6298,ND.0004,Before 1903,N/A,Unprovoked,AUSTRALIA,Western Australia,NaN,Pearl diving,Ahmun,M,...,ND-0004-Ahmun.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0004,ND.0004,5.0,NaN,NaN,0.250000,Unknown
6299,ND.0003,1900-1905,N/A,Unprovoked,USA,North Carolina,Ocracoke Inlet,Swimming,Coast Guard personnel,M,...,ND-0003-Ocracoke_1900-1905.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0003,ND.0003,4.0,NaN,NaN,0.208333,Unknown
6300,ND.0002,1883-1889,N/A,Unprovoked,PANAMA,NaN,"Panama Bay 8ÂºN, 79ÂºW",NaN,Jules Patterson,M,...,ND-0002-JulesPatterson.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0002,ND.0002,3.0,NaN,NaN,0.291667,Unknown
6301,ND.0001,1845-1853,N/A,Unprovoked,CEYLON (SRI LANKA),Eastern Province,"Below the English fort, Trincomalee",Swimming,male,M,...,ND-0001-Ceylon.pdf,http://sharkattackfile.net/spreadsheets/pdf_di...,http://sharkattackfile.net/spreadsheets/pdf_di...,ND.0001,ND.0001,2.0,NaN,NaN,0.166667,Unknown